services:
    db:
        image: mariadb:11.4
        container_name: mariadb
        restart: unless-stopped
        environment:
            MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MARIADB_DATABASE: ${DB_DATABASE}
            MARIADB_USER: ${DB_USERNAME}
            MARIADB_PASSWORD: ${DB_PASSWORD}
        volumes:
          - database_data:/var/lib/mysql
        ports:
          - "3306:3306"
        networks:
          - api-network

    backend:
        container_name: php
        build:
            context: ./
            target: prod
            dockerfile: ./backend/Dockerfile
        image: php83-fpm
        restart: unless-stopped
        working_dir: /var/www/
        environment:
            PHP_OPCACHE_ENABLE: 1
            PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
            PHP_OPCACHE_MAX_ACCELERATED_FILES: 20000
            PHP_OPCACHE_MEMORY_CONSUMPTION: 256
            PHP_OPCACHE_MAX_WASTED_PERCENTAGE: 10
            PHP_OPCACHE_JIT_BUFFER_SIZE: "100M"
            PHP_OPCACHE_JIT: "tracing"
        networks:
            - api-network
        depends_on:
            - proxy
            - db
    frontend:
        container_name: angular_production
        build:
            context: .
            dockerfile: ./frontend/Dockerfile
        restart: unless-stopped
        depends_on:
            - backend
        ports:
            - "80:80"
        networks:
            - api-network
    proxy:
        container_name: nginx
        image: nginx:1.28
        restart: unless-stopped
        expose:
            - 80
        volumes:
            - ./docker/nginx/backend.conf:/etc/nginx/conf.d/default.conf
        networks:
            - api-network
networks:
    api-network:
        driver: bridge
volumes:
    database_data: