services:
    db:
        image: mariadb:11.4.8
        container_name: mariadb
        healthcheck:
          test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u${DB_USERNAME} -p${DB_PASSWORD} >/dev/null 2>&1"]
          interval: 10s
          timeout: 5s
          retries: 5
          start_period: 30s
        environment:
            MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MARIADB_DATABASE: ${DB_DATABASE}
            MARIADB_USER: ${DB_USERNAME}
            MARIADB_PASSWORD: ${DB_PASSWORD}
        volumes:
          - database_data:/var/lib/mysql
        ports:
          - "3306:3306"
        networks:
          - api-network

    backend: &backend_service
        container_name: symfony_api
        build:
            context: ./
            target: prod
            dockerfile: ./backend/Dockerfile
        image: php85-fpm
        restart: unless-stopped
        working_dir: /var/www/
        healthcheck:
            test: ["CMD-SHELL", "ss -ltn | grep -q ':9000' || exit 1"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s
        environment:
            PHP_OPCACHE_ENABLE: 1
            PHP_OPCACHE_VALIDATE_TIMESTAMPS: 0
            PHP_OPCACHE_MAX_ACCELERATED_FILES: 20000
            PHP_OPCACHE_MEMORY_CONSUMPTION: 256
            PHP_OPCACHE_MAX_WASTED_PERCENTAGE: 10
            PHP_OPCACHE_JIT_BUFFER_SIZE: "100M"
            PHP_OPCACHE_JIT: "tracing"
        networks:
            - api-network
        depends_on:
            - proxy
            - db
    frontend:
        container_name: angular_production
        build:
            context: .
            dockerfile: ./frontend/Dockerfile
        restart: unless-stopped
        depends_on:
            - backend
        ports:
            - "80:80"
        networks:
            - api-network
    proxy:
        container_name: nginx
        image: nginx:1.28
        restart: unless-stopped
        expose:
            - 80
        volumes:
            - ./docker/nginx/backend.conf:/etc/nginx/conf.d/default.conf
        networks:
            - api-network
    migrations:
        <<: *backend_service
        container_name: symfony_migrations
        command: [ "php", "bin/console", "doctrine:migrations:migrate", "--no-interaction" ]
        depends_on:
            - db
        restart: on-failure
networks:
    api-network:
        driver: bridge
volumes:
    database_data: