services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.dev
    container_name: angular_dev
    ports: !override
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - api-network
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
  web-server:
    container_name: nginx
    image: nginx:1.24
    restart: unless-stopped
    ports:
        - "80:80"
    volumes:
        - ./backend:/var/www
        - ./docker/nginx/application.dev.conf:/etc/nginx/conf.d/default.conf
    networks:
        - api-network
  backend:
      container_name: php
      build:
          context: ./
          target: dev
          dockerfile: ./backend/Dockerfile
      image: php83-fpm
      restart: unless-stopped
      working_dir: /var/www/
      environment:
          PHP_OPCACHE_ENABLE: 1
          PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
          PHP_OPCACHE_MAX_ACCELERATED_FILES: 20000
          PHP_OPCACHE_MEMORY_CONSUMPTION: 256
          PHP_OPCACHE_MAX_WASTED_PERCENTAGE: 10
          PHP_OPCACHE_JIT_BUFFER_SIZE: "100M"
          PHP_OPCACHE_JIT: "tracing"
      volumes:
          - ./backend:/var/www
          - ./docker/php/conf.d/fpm.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      networks:
          - api-network